eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: WindPFE
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Wind_Coding_Game
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: oumaimazayene4@gmail.com
    password: kody vlus gugu sqhm


    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

dev:
  JDOODLE_CLIENT_ID: 261f93b0f0faeccbcfac701cda4ea3a
  JDOODLE_CLIENT_SECRET: d6e833d076b171ca4798268ddcea3311075d8d4802044cb83adcefeefbd4910f
server:
  port: 8070
